### PR TITLE
Protobuf has changed. Require a less recent version instead.

### PR DESCRIPTION
**Pull request by AlexDev404**
Protobuf has changed. Require a less recent version instead (~3.20.*)

### CODE REVIEW

**Comment by theAkito** [comment]
Why not fix the code to make it able to use the most recent versions?

**Comment by danyeaw** [comment]
Isn't this a duplicate of #39?

**Comment by AlexDev404** [comment]
> 

Not really.

**Comment by vm03** [comment]
duplicate

**Pull request closed without merging**
